name: minote sync

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * *"
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: minote sync
        run: |
          python minote.py "${{secrets.MINOTE_COOKIE}}" "${{secrets.SAVE_DIR}}"
